name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: configure
    #   run: ./configure
    - name: make
      run: make
    # - name: make check
    #   run: make check
    # - name: gcc-build
    #   run: |
    #     gcc -c src/sub.c -o sub.o
    #     gcc -c src/main.c -o main.o -pthread
    #     gcc main.o sub.o -o program -pthread
    # - name: make distcheck
    #   run: make distcheck
